version: "3.5"

services:
    build:
        image: cimg/node:20.18.1-browsers
        working_dir: /nova
        environment:
            - CI
            - CIRCLECI
            - CIRCLE_BRANCH
            - CIRCLE_BUILD_NUM
            - CIRCLE_JOB
            - CIRCLE_NODE_INDEX
            - CIRCLE_NODE_TOTAL
            - CIRCLE_PR_NUMBER
            - CIRCLE_PR_REPONAME
            - CIRCLE_PR_USERNAME
            - CIRCLE_PREVIOUS_BUILD_NUM
            - CIRCLE_PROJECT_REPONAME
            - CIRCLE_PROJECT_USERNAME
            - CIRCLE_SHA1
            - CIRCLE_TAG
            - CIRCLE_USERNAME
            - CIRCLE_WORKFLOW_ID
            - CIRCLE_WORKING_DIRECTORY
            - CIRCLE_API_TOKEN
            - PERCY_TOKEN
            - TEAMCITY_VERSION
            - PACKAGE_VERSION
            - PACKAGE_NAME
            - CUSTOM_VERSION
            - RELEASE_VERSION
            - INCREMENT_TYPE
            - NPM_AUTH
            - PROJECT_DIR
            - SOURCE_BRANCH
            - RELEASE_BRANCH
            - BUILD_BRANCH
            - CREATE_RELEASE_BRANCH
            - SSH_AUTH_SOCK
            - TEAMCITY_PROJECT_NAME
            - MAJOR_PROJECT_NAME
            - MACHINE_URL
            - E2E_BASE_URL=http://web/
            - SELENIUM_ADDRESS=http://selenium:4444/wd/hub
            - CI='true'
        ports:
            - "4200:4200"
            - "49153:49153"
        volumes:
            - "./:/nova:rw"
            - "/root/.ssh:/root/.ssh"
        shm_size: "2gb"
    web:
        image: "nginx"
        volumes:
            - "${PROJECT_DIR}/sdk/api-docs-ng2/examples/browser:/usr/share/nginx/html:ro"
    selenium:
        image: "selenium/standalone-chrome-debug:3.141.59"
        ports:
            - "4444:4444"
            - "5900:5900"
        depends_on:
            - web
        shm_size: "2gb"
